variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:latest

stages:
  - build
  - deploy

Docker_build_job:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
      entrypoint:
        - /bin/sh
      command:
        - -c
        - update-ca-certificates && dockerd-entrypoint.sh
  tags:
    - k8s-testlab
  script:
    - update-ca-certificates
    - echo ${CONTAINER_IMAGE}
    - docker login -u ${CI_REGISTRY_USER} \
      -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}
